SELECT P.PRODUCTLINE,P.PRODUCTCODE,
SUM(O.QUANTITYORDERED) AS TOTAL_UNITS_SOLD,
SUM(O.SALES) AS TOTAL_REVENUE 
FROM PRODUCTS AS P JOIN ORDERDETAILS AS O 
ON P.PRODUCTCODE = O.PRODUCTCODE
GROUP BY P.PRODUCTLINE,P.PRODUCTCODE
ORDER BY TOTAL_REVENUE DESC